groups:
  - name: api-alerts
    rules:
      - alert: HighAPICalls
        expr: rate(my_custom_counter[1m]) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High API call rate detected"
          description: "The API call rate has exceeded 10 per minute."
